runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /review
  script: cdn.app
  login: admin

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: cdn.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
